spring:
  profiles: default

gatekeeper:
  server:
    domain: https://beta-sso-backoffice.woowa.in


---
spring:
  profiles: staging

gatekeeper:
  server:
    domain: https://beta-sso-backoffice.woowa.in
